[phases.setup]
nixPkgs = ["...", "maven", "jdk17"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -Xmx768m -Xms512m -XX:+UseG1GC -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/vendorvault-clm-1.0.0.jar"
