CREATE TABLE IF NOT EXISTS approval_workflows (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  contract_id BIGINT NOT NULL,
  workflow_type VARCHAR(32) NOT NULL DEFAULT 'CONTRACT_APPROVAL',
  status VARCHAR(32) NOT NULL DEFAULT 'IN_PROGRESS',
  total_steps INT NOT NULL DEFAULT 0,
  current_step INT NOT NULL DEFAULT 1,
  initiated_by BIGINT NULL,
  initiated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_workflows_contract FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_workflows_initiated_by FOREIGN KEY (initiated_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

