CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_name VARCHAR(64) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO roles (role_name)
SELECT r.role_name FROM (
  SELECT 'ROLE_SYSTEM_ADMIN' AS role_name UNION ALL
  SELECT 'ROLE_PROCUREMENT_MANAGER' UNION ALL
  SELECT 'ROLE_FINANCE_CONTROLLER' UNION ALL
  SELECT 'ROLE_LEGAL_COUNSEL' UNION ALL
  SELECT 'ROLE_EXECUTIVE_DIRECTOR' UNION ALL
  SELECT 'ROLE_DEPARTMENT_HEAD'
) AS r
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE roles.role_name = r.role_name);

