CREATE TABLE IF NOT EXISTS vendors (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vendor_code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  category VARCHAR(120) NULL,
  pan VARCHAR(16) NOT NULL UNIQUE,
  gstin VARCHAR(20) NULL UNIQUE,
  msme_category VARCHAR(32) NOT NULL DEFAULT 'NONE',
  status VARCHAR(32) NOT NULL DEFAULT 'UNDER_REVIEW',
  blacklist_reason VARCHAR(500) NULL,
  address_line1 VARCHAR(255) NULL,
  address_line2 VARCHAR(255) NULL,
  city VARCHAR(80) NULL,
  state VARCHAR(80) NULL,
  pincode VARCHAR(12) NULL,
  contact_person VARCHAR(120) NULL,
  contact_email VARCHAR(190) NULL,
  contact_phone VARCHAR(32) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

